name: Map Project Actions WorkFlow

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened]
  pull_request_review_comment:
    types: [created]

env:
  WORKFLOWS: |
    issues:
      file: "issues/issue_sync.yaml"
      types: ["opened"]
    issue_comment:
      file: "issues/issue_comment_sync.yaml"
      types: ["created"]
    pull_request:
      file: "pull-requests/pr_sync.yaml"
      types: ["opened"]
    pull_request_comment_create:
      file: "pull-requests/pr_comment_sync.yaml"
      types: ["created"]

jobs:
  choose_and_run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: |
          {% for key, value in fromJson(env.WORKFLOWS).items() %}
            {% if contains(value.types, github.event_name) %}
              - workflow: {{ key }}
                file: {{ value.file }}
            {% endif %}
          {% endfor %}
    steps:
      - name: Run workflow
        if: ${{ matrix.workflow != null }}
        uses: ./${{ matrix.file }}
