name: Map Project Actions WorkFlow

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened]
  pull_request_review_comment:
    types: [created]

env:
  WORKFLOWS: |
    issues:
      file: "issues/issue_sync.yaml"
      types: ["opened"]
    issue_comment:
      file: "issues/issue_comment_sync.yaml"
      types: ["created"]
    pull_request:
      file: "pull-requests/pr_sync.yaml"
      types: ["opened"]
    pull_request_comment_create:
      files: "pull-requests/pr_comment_sync.yaml"
      types: ["created"]

jobs:
  choose_and_run:
      if: ${{ contains(fromJson(env.WORKFLOWS), github.event_name) }}
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Run specific workflow
          uses: ./${{ fromJson(env.WORKFLOWS)[github.event_name].file }}
