name: Map Project Actions WorkFlow

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened]
  pull_request_review_comment:
    types: [created]

env:
  WORKFLOWS: |
    issues:
      file: "issues/issue_sync.yaml"
      types: ["opened"]
    issue_comment:
      file: "issues/issue_comment_sync.yaml"
      types: ["created"]
    pull_request:
      file: "pull-requests/pr_sync.yaml"
      types: ["opened"]
    pull_request_comment_create:
      files: "pull-requests/pr_comment_sync.yaml"
      types: ["created"]

jobs:
  choose_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find matching workflow
        id: find_workflow
        run: |
          WORKFLOWS=$(echo "${{ env.WORKFLOWS }}" | jq -r '.')
          echo "${WORKFLOWS}" | jq -r "to_entries[] | select(.value.types | index(\"${{ github.event_name }}\") != null) | .value + {name: .key}" | jq -s "max_by(.types | length)" > matching_workflow.json
        shell: bash

      - name: Run specific workflow
        if: steps.find_workflow.outputs.name != null
        uses: "./${{ fromJson(steps.find_workflow.outputs.name).file }}"
