name: Check for duplicate issues
on:
  issues:
    types: [opened]
jobs:
  check_duplicate_issues:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check for duplicate issues
        run: |
          title=$(jq --raw-output .issue.title "$GITHUB_EVENT_PATH")
          repo=$(jq --raw-output .repository.full_name "$GITHUB_EVENT_PATH")
          tags=$(jq --raw-output '.issue.labels | map(.name) | join(",")' "$GITHUB_EVENT_PATH")
          duplicate=$(gh issue list --state=all --labels="$tags" --title="$title" | grep -o "$repo")
          if [[ -n "$duplicate" ]]; then
            echo "An issue with the same title and labels already exists in $duplicate"
            gh issue close "$(jq --raw-output .issue.number "$GITHUB_EVENT_PATH")"
            exit 1
          fi
