name: Sync Project Issues

on:
  issues:
    types: [opened]

jobs:
  install_gh_cli:
    runs-on: ubuntu-latest
    steps:
      - name: Install gh CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh
  check_duplicate:
    runs-on: ubuntu-latest
    needs: install_gh_cli
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check for duplicate issues
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          title=$(jq --raw-output .issue.title "$GITHUB_EVENT_PATH")
          repo=$(jq --raw-output .repository.full_name "$GITHUB_EVENT_PATH")
          duplicate=$(gh issue list --state=all --label=duplicate --search="$title" | grep -o "$repo")
          if [[ -n "$duplicate" ]]; then
            echo "An issue with the same title already exists in $duplicate"
            gh issue add-label ${GITHUB_EVENT_NUMBER} duplicate
            gh issue close ${GITHUB_EVENT_NUMBER}
            exit 1
          else
            echo "No duplicate issues found, proceeding with sync"
            exit 0
          fi

  sync_issues:
    runs-on: ubuntu-latest
    needs: check_duplicate
    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v2
        with:
          repository: ALCHElVlY/diabloii-market
      
      - name: Checkout Private Repo
        uses: actions/checkout@v2
        with:
          repository: ALCHElVlY/DiabloIIMarket-source
          token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}

      - name: Create Issue in Private Repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          issue_title=$(echo "${{ github.event.issue.title }}")
          issue_body=$(echo "${{ github.event.issue.body }}")
          label=$(echo "${{ github.event.issue.labels[0].name }}")
          gh issue create -t "${issue_title}" -b "${issue_body}" -l "${label}" -R https://github.com/ALCHElVlY/DiabloIIMarket-source
