name: Sync Project Issues

on:
  issues:
    types: [opened]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v2
        with:
          repository: ALCHElVlY/diabloii-market
      
      - name: Checkout Private Repo
        uses: actions/checkout@v2
        with:
          repository: ALCHElVlY/DiabloMarket-source
          token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}

      - name: Create Issue in Private Repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          issue_title=$(echo "${{ github.event.issue.title }}" | tr ' ' '_')
          issue_body=$(echo "${{ github.event.issue.body }}" | tr '\n' '\\n')
          label=$(echo "${{ github.event.issue.labels[0].name }}")
          gh issue create -t "${issue_title}" -b "${issue_body}" -l "${label}" -R https://github.com/ALCHElVlY/DiabloMarket-source
      - name: Push changes to Private Repo
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git add .
          git commit -m "Syncing issues.."
          git push
